project:
  type: website

website:
  title: "ISSS624_Geospatial_Analytics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right: 
      - text: Hands-on Ex
        menu: 
          - text: Hands-on Ex01
          - text: Hands-on Ex02
          - text: Hands-on Ex03
          - text: Hands-on Ex04
          - text: Hands-on Ex05
      - text: In-class Ex
        menu: 
          - text: In-class Ex01
          - text: In-class Ex02
          - text: In-class Ex03
          - text: In-class Ex04
          - text: In-class Ex05
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

